version: "3.8"

services:
  static-webapp:
    image: nginx:alpine
    container_name: static-webapp
    restart: always
    ports:
      - "80:8001"
    volumes:
      - ./static-webapp:/usr/share/nginx/html:ro
      - ./static-webapp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
