version: "3.8"

services:
  static-webapp:
    image: nginx:alpine-slim

    restart: always
    ports:
      - "80:8001"
    volumes:

      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - frontend_network

networks:
  frontend_network:
    name: frontend_network
    driver: bridge