version: "3.8"

services:
  flask-api:
    image: raphmn/flask-api:latest
    container_name: flask-api
    restart: always
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    driver: bridge
