version: "3.8"

services:
  reverse-proxy:

    image: nginx:alpine-slim
    restart: always
    ports:
      - "81:81"
      - "82:82"
      - "83:83"
    volumes:

      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    name: reverse_proxy_network
    driver: bridge