version: "3.8"

services:
  flask-front:

    image: raphmn/flask-front:latest
    restart: always
    networks:
      - reverse_proxy_network

networks:
  reverse_proxy_network:
    name: reverse_proxy_network
    driver: bridge